### ISSUE TITLE
Cannot make an activity _never_ connected to a role

### ISSUE THREAD

**Issue by OdyX** [sephii/taxi-zebra#12]
Some activities such as `infra_daily` are (currently) meant to spread across multiple roles, and answering "no" to `Make the infra_daily alias always use this role? [Y/n]` every single time doesn't scale. What about adding a third "Never again" option, with a `role` in the `(project, activity, role)` tuple set to `0`?

https://github.com/sephii/taxi-zebra/blob/65be35dbf45c8b19e9c386a3813a7bedd95a70bd/taxi_zebra/backend.py#L248

**Comment by jeanmonod** [comment]
Really good idea! I'd loved to be able to continue using `_internal` and to decide at commit time what role to use...
