### ISSUE TITLE
Shouldn't we split the Zebra binding from the taxi backend?

### ISSUE THREAD

**Issue by etoulas** [sephii/taxi-zebra#2]
Hi,

I was wondering why we don't have a general Zebra binding for Python instead of an API that is very tightly coupled with taxi.

The backends are a great mechanism for taxi! The Zebra backend imports lots of taxi modules, which I would try to avoid.

Taxi-zebra should implement the specific interface of BaseBackend to work together with taxi. The actual connection and API specifics should go into zebra (or pyzebra, or python-zebra).

Rough architecture:
1. taxi
2. taxi-zebra (backend)
3. zebra (API)

Let's discuss ;)

Tim

**Comment by sephii** [comment]
Hi Tim,

Sorry for the delay, for some reason I didn't get any notification for this issue.

I agree with you it would be nice to have a Zebra Python library. The thing is, Zebra doesn't have (and probably won't have, at least in the near future) any API we could rely on. If we still want to separate the actual Zebra logic from the backend logic, maybe we could still create a zebra module in taxi-zebra, and this would be a first step towards decoupling?

I'm really interested by how you would avoid importing stuff from the `taxi` module. Would you create methods on the `BaseBackend` class, for example to retrieve a mapping from the aliases database? Do you see a cleaner way to do that?

**Comment by jeanmonod** [comment]
Personally I think that it will be a waste of time to implement a Zebra Library over a bad Zebra interface. We should instead invest time to build a clean REST API on Zebra.
