### ISSUE TITLE
Doesn't take "active" status for activities into account

### ISSUE THREAD

**Issue by OdyX** [sephii/taxi-zebra#23]
In recent zebra, activities can be set to "inactive", and taxi + taxi-zebra doesn't take this into account at all.

**Comment by jeanmonod** [comment]
> In recent zebra

On Zebra, It's possible to turn an activity as "inactive" since January 2013 😅

**Comment by OdyX** [comment]
It turns out… It's easy to have `taxi-zebra` just ignore inactive entries; but as there's special-casing of inactive (or finished) projects directly in `taxi`, it's much cleaner to have that done in `taxi`; https://github.com/sephii/taxi/pull/147 I'll check with @sephii to get that merged.
