### ISSUE TITLE
Compatibility with Zebra 2.X

### ISSUE THREAD

**Issue by jeanmonod** [sephii/taxi-zebra#3]

**Comment by sephii** [comment]
Can you provide some information on the structure changes of 2.X?

**Comment by jeanmonod** [comment]
No, I can't.
We have identified the change on the new timesheet form, but for this one, we can eventually provide a backward compatibility.
For the rest, as I don't know how taxi is working, I suggest to run a full functional test on https://beta-zebra.liip.ch. If you want to have information about what we did, you can check all changes since 1.18.0 in https://gitlab.liip.ch/liip/zebra/blob/responsive/CHANGELOG

**Comment by sephii** [comment]
The only impacted commands are `commit` and `update`. The `update` command is still working fine, however the `commit` doesn't work anymore (I guess because of the new form).

**Comment by jeanmonod** [comment]
!important; Taxi is no more working :(

**Comment by sephii** [comment]
`commit` command is fixed in 1.0.5, we still need `activity_aliases` to be fixed on the Zebra side to get the `update` command to work.
