### ISSUE TITLE
Add subject to "taxi start" command

### ISSUE THREAD

**Issue by kevinmoilar** [sephii/taxi-zebra#7]
**As a Liiper** I would like to **add a description** to the taxi start command in order **be more efficient** by avoiding additional editing after 'taxi stop'.

Example: 
`taxi start ioc_365_po 'IOC365-4 analyse current plugins'`

**Comment by sephii** [comment]
Hi @kevinmoilar, 

Thanks for the proposal. I've moved it to https://github.com/sephii/taxi since it's not zebra-specific.

Cheers,
Sylvain
