### ISSUE TITLE
Handle Zebra warning

### ISSUE THREAD

**Issue by jeanmonod** [sephii/taxi-zebra#8]
On the zebra side, we have timesheet creation warnings display on screen. See https://github.com/liip/zebra/blob/master/localinc/api/command/timesheet.php#L161

How can we handle to have the same concept in taxi?

**Comment by sephii** [comment]
I see two solutions:

1. Implement the check directly in Taxi
2. Make the server respond with a 4xx status code and return the warning in the HTTP response body. Taxi could then show the warning, ask for a confirmation, and re-submit the entry, adding a specific header like `X-Force: 1`, or a specific POST parameter

What do you think?

**Comment by jeanmonod** [comment]
We only speak about warning messages. No need to prevent submission of the entry. Currently on submit, you go this:

    {
      "success": true,
      "data": {
        "id": 698063,
        "url": "https://zebra.liip.ch/api/v2/timesheets/698063"
      }
    }

Why If I return you something like 

    {
      "success": true,
      "data": { ... },
      "warning": "Message XY"
    }

And you display this next to the confirmation?

**Comment by sephii** [comment]
Ah yes, I thought the goal was to have something blocking. Your proposal looks OK, I would just use a key like `message` instead of `warning` so we could use it for any kind of notifications, not just for warnings.

**Comment by jeanmonod** [comment]
Let's do it like on Zebra then. In Zebra why add an http header like this one:

![image](https://user-images.githubusercontent.com/114489/41459459-f17be1a4-7089-11e8-99d5-e501f0ee8e24.png)

We could reuse the same format in the API. But instead of an header, it will be in the JSON response

Ok for you?

**Comment by sephii** [comment]
:+1:

**Comment by sephii** [comment]
Implemented in 1.4.0.
